### ISSUE TITLE
failed to login 

### ISSUE THREAD

**Issue by CharlesGC** [thomaswangio/vue-admin-dashboard#14]
When I try to log in with user name support@designcode.io and password 123456789, it will prompt login failure
![image](https://user-images.githubusercontent.com/18606255/83990904-b7549000-a97d-11ea-8a84-80a80a5edcf0.png)
I don't know why

**Comment by ghost** [comment]
Hey @CharlesGC so this is because Netlify recently changed their domain for projects to `netlify.app`. I pushed an update to fix this in the Netlify Identity configuration:

```
// Initialize GoTrue JS for Netlify
export const auth = new GoTrue({
  APIUrl: "https://vue-hq.netlify.app/.netlify/identity",
  setCookie: true,
});
```

https://github.com/thomaswang/vue-admin-dashboard/blob/master/src/main.js

**Comment by ghost** [comment]
I also had to update the `firebase/app` dependency. It should be in working order now after the new site builds!

**Comment by ghost** [comment]
@CharlesGC please use https://vue-hq-2.netlify.app now to access the demo since I no longer have access to the original url. Sorry for the inconvenience!
