### ISSUE TITLE
scss indentation problem

### ISSUE THREAD

**Issue by wjx0820** [thomaswangio/vue-admin-dashboard#4]
I wonder why need these indentation here, and also Prettier fix the indentation for me when I save so I cannot be the save with yours. Could you explain why? Thanks! 

![image](https://user-images.githubusercontent.com/31770433/58146546-2e42bc00-7c89-11e9-84ed-6da3681b24d7.png)

**Comment by ghost** [comment]
Hmm good catch @Jexxie, sorry about that not sure why Prettier didn't catch this one for me. Fixed: https://github.com/thomaswangio/vue-admin-dashboard/commit/579aa281c4bd69e9cdf136236ff55f95fdc61197
